name: AWS CloudFormation Workflow
on: workflow_dispatch

jobs:
  cloudformation-deployment:
    name: AWS CloudFormation Deployment
    runs-on: ubuntu-latest
    env:
      aws-region: us-east-2

    steps:
      - name: Authenticate against AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws-region }}
